CLASS zrap110_travel_event_handl_039 DEFINITION
  PUBLIC
  FINAL FOR EVENTS OF zrap110_r_traveltp_039
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZRAP110_TRAVEL_EVENT_HANDL_039 IMPLEMENTATION.
ENDCLASS.
